# Generated by Django 6.0.2 on 2026-05-19 23:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, null=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_stripe_webhook_event',
                'indexes': [models.Index(fields=['event_type', '-received_at'], name='billing_str_event_t_a26da7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.IntegerField(default=0, help_text='Integer credits — never fractional.')),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('auto_recharge_enabled', models.BooleanField(default=False)),
                ('auto_recharge_threshold', models.IntegerField(default=0)),
                ('auto_recharge_package', models.CharField(blank=True, max_length=32, null=True)),
                ('low_balance_alert', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_wallet',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('team', 'Team'), ('enterprise', 'Enterprise')], default='free', max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('incomplete', 'Incomplete')], default='active', max_length=16)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'billing_subscription',
                'indexes': [models.Index(fields=['stripe_customer_id'], name='billing_sub_stripe__97887e_idx'), models.Index(fields=['stripe_subscription_id'], name='billing_sub_stripe__abc269_idx')],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('credit_purchase', 'Credit Purchase'), ('transcription_charge', 'Transcription Charge'), ('ai_charge', 'AI Charge'), ('subscription_bonus', 'Subscription Bonus'), ('refund', 'Refund'), ('adjustment', 'Manual Adjustment')], max_length=32)),
                ('amount_cents', models.IntegerField(blank=True, null=True)),
                ('credits_delta', models.IntegerField(help_text='Positive = credit, negative = debit.')),
                ('balance_after', models.IntegerField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='billing.wallet')),
            ],
            options={
                'db_table': 'billing_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='billing_tra_wallet__6c38e4_idx'), models.Index(fields=['type'], name='billing_tra_type_e9bf79_idx')],
            },
        ),
    ]
