# Generated by Django 6.0.7 on 2026-08-30 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_credit_debt_and_idempotency_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='merged_into',
            field=models.ForeignKey(blank=True, help_text="The wallet this one's credits and ledger were moved into when its owner was folded into another account (auth's user.merged). Non-NULL means this wallet is CLOSED at zero: it is kept as the record that the guest's credits existed and where they went, not deleted. NULL for every live wallet.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_wallets', to='billing.wallet'),
        ),
    ]
