# Generated by Django 6.0.7 on 2026-09-12 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_wallet_merged_into'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False, help_text="The subscriber asked to stop and the provider will not renew. Stripe keeps `status` at 'active' for the whole paid-for remainder — service is owed until current_period_end — so this flag is the ONLY thing that distinguishes 'subscribed' from 'leaving on the 30th'. Without it a UI must either keep offering Cancel to someone who already cancelled, or cut off a period the customer paid for."),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('unpaid', 'Unpaid'), ('paused', 'Paused')], default='active', help_text="Mirrors the provider's subscription status. 32 chars because 'incomplete_expired' is 18 — the old 16 could not hold it.", max_length=32),
        ),
    ]
